### ISSUE TITLE
Mod Request

### ISSUE THREAD

**Issue by tqoac** [Darkstar6423/ZombiU-Mod-Loader#2]
i dont want to sound pushy but here goes, i want to request a mad that will allow you to type in a code or press a button and it would give you every single gun in the game, there was this mod that i used all the time https://github.com/Xekep/ZOMBIZDER that would act like a cheat code enterer, if you entered the code iddqd you would give you all weapons, if you entered in idkfa you would enter god mod etc etc, but when uplay changed their name it broke,i was wondering if you could replicate that as a mod as i dont have any modding experience

**Comment by Darkstar6423** [comment]
I do have plans to add a dev console to the loader that would have features like this, however my backend does not currently support giving weapons, I still need to work on that since I'm still in a very early stage of development.

**Comment by Zurek0x** [comment]
@Darkstar6423 I may be able to help to a degree in the dev console area for giving items and weapons.
I have already made a private trainer (Written in C++) And can offer a great deal of help if you want to collab!

My discord is here -> **Külf#0001**

**Comment by Zurek0x** [comment]
> I do have plans to add a dev console to the loader that would have features like this, however my backend does not currently support giving weapons, I still need to work on that since I'm still in a very early stage of development.

@Darkstar6423 I may be able to help to a degree in the dev console area for giving items and weapons.
I have already made a private trainer (Written in C++) And can offer a great deal of help if you want to collab!

My discord is here -> **Külf#0001**
