### ISSUE TITLE
Is this still in development?

### ISSUE THREAD

**Issue by VERsingthegamez** [Darkstar6423/ZombiU-Mod-Loader#3]
I'd love to get a copy of this game if it is and help give feedback. Trying this game out on ps4, there's some serious improvements needed to make the game feel more playable in my eyes and less clunky.

**Comment by Darkstar6423** [comment]
Yes, I am still working on this project. Sometimes I have to slow development when work picks up. I would love to hear your feedback!

**Comment by VERsingthegamez** [comment]
Game is on sale so bought a copy for $5. I'll give it a run and see what I run into. Do you have any plans to implement this mod into your mod to fix some bugs as well as add fov options? https://github.com/i64-sudo/ZombiU_XPatcher
